# PubMed RAG: Dense Embedding & Chroma Vector Store Pipeline

## Settings

In [1]:
import os
import sys
import time
from pathlib import Path

import torch
import pandas as pd
from dotenv import load_dotenv, find_dotenv

# -------------------------
# Load environment variables
# -------------------------
load_dotenv(find_dotenv())

# -------------------------
# Add project root to path
# -------------------------
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

from src.chroma_manager import ChromaManager

# -------------------------
# Config
# -------------------------
SEED = int(os.environ.get("SEED", 42))
DATA_DIR = Path(os.environ.get("DATA_DIR", "/workspace/data"))

CHUNK_DIR = DATA_DIR / "chunked_docs"
VECTOR_DIR = DATA_DIR / "vector_store"
BM25_DIR = DATA_DIR / "bm25_index"

# -------------------------
# Ensure directories exist
# -------------------------
CHUNK_DIR.mkdir(parents=True, exist_ok=True)
VECTOR_DIR.mkdir(parents=True, exist_ok=True)
BM25_DIR.mkdir(parents=True, exist_ok=True)

# -------------------------
# Ensure directories exist
# -------------------------
CHUNK_DIR.mkdir(parents=True, exist_ok=True)
VECTOR_DIR.mkdir(parents=True, exist_ok=True)

# -------------------------
# Environment Info
# -------------------------
print(f"SEED: {SEED}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"PyTorch version: {torch.__version__}")
print(f"Chunk dir: {CHUNK_DIR}")
print(f"Vector DB dir: {VECTOR_DIR}")

2026-03-12 12:07:11.309990019 [W:onnxruntime:Default, device_discovery.cc:164 DiscoverDevicesForPlatform] GPU device discovery failed: device_discovery.cc:89 ReadFileContents Failed to open file: "/sys/class/drm/card0/device/vendor"
/opt/conda/lib/python3.10/site-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(

SEED: 42
CUDA available: True
PyTorch version: 2.2.0
Chunk dir: /workspace/data/chunked_docs
Vector DB dir: /workspace/data/vector_store

## Helpers

In [9]:
import spacy
from tqdm import tqdm

# -------------------------
# Load spaCy model
# -------------------------

nlp = spacy.load(
    "en_core_sci_sm",
    disable=["parser", "ner", "tagger", "lemmatizer"]
)

# -------------------------
# Helper: tokenize a spaCy doc
# -------------------------

def tokenize_spacy_doc(doc):
    return [
        token.text.lower()
        for token in doc
        if not token.is_punct and not token.is_space
    ]


# -------------------------
# Helper: tokenize list of texts
# -------------------------

def spacy_tokenize_texts(texts, batch_size=64):
    tokenized = []

    for doc in tqdm(
        nlp.pipe(texts, batch_size=batch_size),
        total=len(texts),
        desc="spaCy tokenizing"
    ):
        tokenized.append(tokenize_spacy_doc(doc))

    return tokenized

## 1. Section-Aware Chunking (400 Tokens)

In [23]:
section_chunks_df = pd.read_csv(f"{CHUNK_DIR}/chunks_section_400token.csv")

In [40]:
db = ChromaManager(
    base_directory=VECTOR_DIR,
    chunk_strategy="section_400token",
    embedding_model="pubmedbert",
    collection_name="medical_rag"
)

Loading embedding model: pritamdeka/S-PubMedBert-MS-MARCO

Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given

Vector DB ready → /workspace/data/vector_store/section_400token/pubmedbert

In [25]:
db.reset()

Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given

Collection reset.

### Embedding Generation and Vector Database Construction

In [26]:
start = time.time()

# db_section.add_chunks(section_chunks_df)

elapsed = time.time() - start

print(f"\nInserted {len(section_chunks_df)} chunks")
print(f"Total time: {elapsed:.2f} seconds")
print(f"Avg time per chunk: {elapsed/len(section_chunks_df):.4f} sec")

Preparing chunks:   0% 0/109234 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Failed to send telemetry event CollectionAddEvent: capture() takes 1 positional argument but 3 were given
Preparing chunks:   0% 256/109234 [00:03<22:29, 80.77it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   0% 512/109234 [00:05<20:54, 86.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   1% 768/109234 [00:08<20:35, 87.78it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   1% 1024/109234 [00:11<20:38, 87.39it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   1% 1280/109234 [00:14<19:06, 94.12it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   1% 1536/109234 [00:17<19:45, 90.88it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   2% 1792/109234 [00:19<19:35, 91.38it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   2% 2048/109234 [00:22<19:24, 92.03it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   2% 2304/109234 [00:25<19:08, 93.07it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   2% 2560/109234 [00:27<18:37, 95.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   3% 2816/109234 [00:30<19:26, 91.19it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   3% 3072/109234 [00:34<20:11, 87.62it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   3% 3328/109234 [00:36<19:45, 89.32it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   3% 3584/109234 [00:39<18:57, 92.90it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   4% 3840/109234 [00:42<19:17, 91.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   4% 4096/109234 [00:45<20:05, 87.22it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   4% 4352/109234 [00:48<20:12, 86.53it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   4% 4608/109234 [00:51<19:36, 88.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   4% 4864/109234 [00:54<20:14, 85.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   5% 5120/109234 [00:57<21:11, 81.86it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   5% 5376/109234 [01:00<19:58, 86.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   5% 5632/109234 [01:03<20:09, 85.68it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   5% 5888/109234 [01:07<22:23, 76.93it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   6% 6144/109234 [01:10<22:01, 78.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   6% 6400/109234 [01:13<20:21, 84.15it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   6% 6656/109234 [01:15<19:28, 87.80it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   6% 6912/109234 [01:19<19:55, 85.58it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   7% 7168/109234 [01:22<20:46, 81.91it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   7% 7424/109234 [01:25<19:59, 84.88it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   7% 7680/109234 [01:28<19:50, 85.33it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   7% 7936/109234 [01:31<19:38, 85.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   7% 8192/109234 [01:34<21:03, 79.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   8% 8448/109234 [01:37<20:33, 81.70it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   8% 8704/109234 [01:40<20:03, 83.55it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   8% 8960/109234 [01:43<19:18, 86.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   8% 9216/109234 [01:46<20:04, 83.04it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   9% 9472/109234 [01:49<18:49, 88.35it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   9% 9728/109234 [01:51<17:55, 92.55it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   9% 9984/109234 [01:54<17:29, 94.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   9% 10240/109234 [01:58<19:15, 85.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  10% 10496/109234 [02:00<18:17, 89.98it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  10% 10752/109234 [02:03<17:50, 92.03it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  10% 11008/109234 [02:07<21:23, 76.50it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  10% 11264/109234 [02:11<21:42, 75.19it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  11% 11520/109234 [02:13<19:57, 81.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  11% 11776/109234 [02:16<19:04, 85.12it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  11% 12032/109234 [02:20<20:25, 79.30it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  11% 12288/109234 [02:23<19:42, 81.99it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  11% 12544/109234 [02:26<19:37, 82.11it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  12% 12800/109234 [02:29<19:36, 81.95it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  12% 13056/109234 [02:32<20:17, 78.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  12% 13312/109234 [02:35<18:57, 84.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  12% 13568/109234 [02:38<18:08, 87.89it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  13% 13824/109234 [02:41<19:03, 83.44it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  13% 14080/109234 [02:45<20:35, 77.05it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  13% 14336/109234 [02:48<19:44, 80.14it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  13% 14592/109234 [02:51<18:53, 83.52it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  14% 14848/109234 [02:54<18:35, 84.60it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  14% 15104/109234 [02:57<19:37, 79.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  14% 15360/109234 [03:00<19:15, 81.22it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  14% 15616/109234 [03:03<18:28, 84.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  15% 15872/109234 [03:06<18:16, 85.11it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  15% 16128/109234 [03:10<19:22, 80.08it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  15% 16384/109234 [03:12<18:17, 84.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  15% 16640/109234 [03:16<19:47, 77.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  15% 16896/109234 [03:19<19:37, 78.39it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  16% 17152/109234 [03:23<20:41, 74.17it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  16% 17408/109234 [03:26<19:06, 80.07it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  16% 17664/109234 [03:28<17:59, 84.81it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  16% 17920/109234 [03:32<18:05, 84.15it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  17% 18176/109234 [03:35<19:12, 78.99it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  17% 18432/109234 [03:38<18:29, 81.84it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  17% 18688/109234 [03:41<18:13, 82.80it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  17% 18944/109234 [03:44<17:34, 85.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  18% 19200/109234 [03:48<19:11, 78.17it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  18% 19456/109234 [03:51<18:44, 79.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  18% 19712/109234 [03:54<17:56, 83.13it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  18% 19968/109234 [03:56<17:14, 86.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  19% 20224/109234 [04:00<18:49, 78.82it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  19% 20480/109234 [04:04<19:14, 76.84it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  19% 20736/109234 [04:07<18:33, 79.49it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  19% 20992/109234 [04:10<17:57, 81.89it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  19% 21248/109234 [04:14<19:43, 74.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  20% 21504/109234 [04:16<18:19, 79.80it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  20% 21760/109234 [04:20<17:59, 81.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  20% 22016/109234 [04:24<20:13, 71.89it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  20% 22272/109234 [04:29<22:18, 64.98it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  21% 22528/109234 [04:34<24:07, 59.89it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  21% 22784/109234 [04:39<25:07, 57.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  21% 23040/109234 [04:44<26:36, 53.99it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  21% 23296/109234 [04:47<24:05, 59.46it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  22% 23552/109234 [04:50<21:34, 66.20it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  22% 23808/109234 [04:53<19:20, 73.63it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  22% 24064/109234 [04:57<19:50, 71.55it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  22% 24320/109234 [05:00<19:14, 73.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  22% 24576/109234 [05:03<18:41, 75.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  23% 24832/109234 [05:06<17:17, 81.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  23% 25088/109234 [05:09<17:40, 79.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  23% 25344/109234 [05:12<16:49, 83.12it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  23% 25600/109234 [05:15<16:06, 86.56it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  24% 25856/109234 [05:18<16:45, 82.95it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  24% 26112/109234 [05:22<17:46, 77.95it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  24% 26368/109234 [05:24<16:48, 82.15it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  24% 26624/109234 [05:27<16:13, 84.87it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  25% 26880/109234 [05:30<16:07, 85.16it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  25% 27136/109234 [05:35<18:14, 75.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  25% 27392/109234 [05:38<18:26, 73.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  25% 27648/109234 [05:41<17:23, 78.19it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  26% 27904/109234 [05:44<16:50, 80.52it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  26% 28160/109234 [05:48<17:43, 76.23it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  26% 28416/109234 [05:50<16:25, 82.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  26% 28672/109234 [05:53<15:40, 85.66it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  26% 28928/109234 [05:56<15:50, 84.45it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  27% 29184/109234 [06:00<17:39, 75.52it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  27% 29440/109234 [06:03<16:02, 82.90it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  27% 29696/109234 [06:06<15:49, 83.81it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  27% 29952/109234 [06:09<15:50, 83.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  28% 30208/109234 [06:13<17:19, 76.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  28% 30464/109234 [06:16<16:26, 79.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  28% 30720/109234 [06:18<15:49, 82.73it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  28% 30976/109234 [06:21<15:21, 84.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  29% 31232/109234 [06:26<17:20, 74.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  29% 31488/109234 [06:28<16:13, 79.84it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  29% 31744/109234 [06:31<15:00, 86.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  29% 32000/109234 [06:35<16:54, 76.14it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  30% 32256/109234 [06:38<16:09, 79.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  30% 32512/109234 [06:41<16:06, 79.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  30% 32768/109234 [06:46<17:56, 71.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  30% 33024/109234 [06:50<18:52, 67.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  30% 33280/109234 [06:53<17:14, 73.40it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  31% 33536/109234 [06:55<16:06, 78.30it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  31% 33792/109234 [06:58<15:11, 82.78it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  31% 34048/109234 [07:02<16:43, 74.89it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  31% 34304/109234 [07:05<15:21, 81.34it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  32% 34560/109234 [07:08<14:39, 84.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  32% 34816/109234 [07:10<13:55, 89.04it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  32% 35072/109234 [07:14<15:34, 79.32it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  32% 35328/109234 [07:17<15:30, 79.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  33% 35584/109234 [07:20<14:29, 84.72it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  33% 35840/109234 [07:22<13:38, 89.66it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  33% 36096/109234 [07:26<15:22, 79.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  33% 36352/109234 [07:29<14:20, 84.67it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  34% 36608/109234 [07:32<13:46, 87.87it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  34% 36864/109234 [07:35<14:10, 85.12it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  34% 37120/109234 [07:38<14:57, 80.32it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  34% 37376/109234 [07:41<14:05, 85.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  34% 37632/109234 [07:44<13:31, 88.22it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  35% 37888/109234 [07:47<13:37, 87.30it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  35% 38144/109234 [07:52<16:27, 71.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  35% 38400/109234 [07:56<17:28, 67.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  35% 38656/109234 [07:58<15:23, 76.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  36% 38912/109234 [08:01<14:44, 79.48it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  36% 39168/109234 [08:06<16:03, 72.76it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  36% 39424/109234 [08:09<15:26, 75.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  36% 39680/109234 [08:11<14:25, 80.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  37% 39936/109234 [08:14<13:34, 85.13it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  37% 40192/109234 [08:18<14:59, 76.76it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  37% 40448/109234 [08:21<14:19, 80.07it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  37% 40704/109234 [08:24<13:38, 83.75it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  37% 40960/109234 [08:27<13:32, 84.07it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  38% 41216/109234 [08:31<14:40, 77.21it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  38% 41472/109234 [08:34<14:06, 80.09it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  38% 41728/109234 [08:36<12:50, 87.58it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  38% 41984/109234 [08:38<12:17, 91.21it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  39% 42240/109234 [08:43<14:07, 79.04it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  39% 42496/109234 [08:45<13:14, 84.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  39% 42752/109234 [08:48<12:52, 86.03it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  39% 43008/109234 [08:52<14:16, 77.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  40% 43264/109234 [08:55<13:56, 78.91it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  40% 43520/109234 [08:59<14:53, 73.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  40% 43776/109234 [09:03<15:28, 70.50it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  40% 44032/109234 [09:09<18:04, 60.14it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  41% 44288/109234 [09:13<18:08, 59.67it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  41% 44544/109234 [09:18<18:24, 58.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  41% 44800/109234 [09:21<16:39, 64.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  41% 45056/109234 [09:25<16:11, 66.07it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  41% 45312/109234 [09:27<14:52, 71.61it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  42% 45568/109234 [09:30<13:19, 79.62it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  42% 45824/109234 [09:33<12:50, 82.28it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  42% 46080/109234 [09:37<14:08, 74.40it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  42% 46336/109234 [09:40<13:16, 78.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  43% 46592/109234 [09:42<12:22, 84.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  43% 46848/109234 [09:45<11:44, 88.53it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  43% 47104/109234 [09:49<12:57, 79.88it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  43% 47360/109234 [09:52<12:40, 81.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  44% 47616/109234 [09:54<11:55, 86.11it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  44% 47872/109234 [09:57<11:25, 89.56it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  44% 48128/109234 [10:01<13:00, 78.34it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  44% 48384/109234 [10:04<12:49, 79.04it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  45% 48640/109234 [10:07<11:51, 85.22it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  45% 48896/109234 [10:11<12:56, 77.73it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  45% 49152/109234 [10:15<14:04, 71.16it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  45% 49408/109234 [10:18<12:59, 76.70it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  45% 49664/109234 [10:20<12:10, 81.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  46% 49920/109234 [10:23<11:17, 87.51it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  46% 50176/109234 [10:27<12:46, 77.04it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  46% 50432/109234 [10:30<11:52, 82.48it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  46% 50688/109234 [10:32<11:00, 88.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  47% 50944/109234 [10:35<10:40, 91.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  47% 51200/109234 [10:39<12:07, 79.77it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  47% 51456/109234 [10:42<12:07, 79.44it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  47% 51712/109234 [10:45<11:31, 83.13it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  48% 51968/109234 [10:47<10:52, 87.72it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  48% 52224/109234 [10:51<12:02, 78.90it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  48% 52480/109234 [10:54<11:22, 83.14it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  48% 52736/109234 [10:57<10:54, 86.35it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  49% 52992/109234 [11:00<10:56, 85.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  49% 53248/109234 [11:04<12:17, 75.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  49% 53504/109234 [11:07<11:36, 80.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  49% 53760/109234 [11:10<10:59, 84.07it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  49% 54016/109234 [11:13<11:49, 77.82it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  50% 54272/109234 [11:17<12:16, 74.64it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  50% 54528/109234 [11:20<11:56, 76.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  50% 54784/109234 [11:23<10:55, 83.08it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  50% 55040/109234 [11:27<11:40, 77.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  51% 55296/109234 [11:29<11:05, 81.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  51% 55552/109234 [11:32<10:50, 82.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  51% 55808/109234 [11:35<10:42, 83.18it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  51% 56064/109234 [11:39<11:38, 76.13it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  52% 56320/109234 [11:43<11:17, 78.11it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  52% 56576/109234 [11:45<10:35, 82.80it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  52% 56832/109234 [11:48<09:55, 87.95it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  52% 57088/109234 [11:51<10:44, 80.88it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  52% 57344/109234 [11:54<10:10, 84.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  53% 57600/109234 [11:57<09:44, 88.28it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  53% 57856/109234 [11:59<09:30, 90.04it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  53% 58112/109234 [12:04<10:45, 79.20it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  53% 58368/109234 [12:07<10:42, 79.20it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  54% 58624/109234 [12:10<10:21, 81.39it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  54% 58880/109234 [12:13<09:58, 84.19it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  54% 59136/109234 [12:17<11:24, 73.20it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  54% 59392/109234 [12:20<10:20, 80.35it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  55% 59648/109234 [12:23<10:53, 75.84it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  55% 59904/109234 [12:27<10:51, 75.74it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  55% 60160/109234 [12:31<11:24, 71.67it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  55% 60416/109234 [12:34<10:49, 75.14it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  56% 60672/109234 [12:37<10:08, 79.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  56% 60928/109234 [12:40<09:57, 80.88it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  56% 61184/109234 [12:44<10:45, 74.44it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  56% 61440/109234 [12:46<09:58, 79.89it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  56% 61696/109234 [12:49<09:22, 84.53it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  57% 61952/109234 [12:52<09:00, 87.44it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  57% 62208/109234 [12:56<09:50, 79.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  57% 62464/109234 [12:59<09:44, 79.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  57% 62720/109234 [13:02<09:24, 82.40it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  58% 62976/109234 [13:05<09:14, 83.46it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  58% 63232/109234 [13:09<10:09, 75.53it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  58% 63488/109234 [13:12<09:35, 79.46it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  58% 63744/109234 [13:15<09:33, 79.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  59% 64000/109234 [13:19<10:08, 74.38it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  59% 64256/109234 [13:22<09:32, 78.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  59% 64512/109234 [13:24<09:00, 82.78it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  59% 64768/109234 [13:27<08:40, 85.37it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  60% 65024/109234 [13:31<09:39, 76.23it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  60% 65280/109234 [13:36<10:37, 68.90it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  60% 65536/109234 [13:40<11:12, 64.98it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  60% 65792/109234 [13:45<11:59, 60.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  60% 66048/109234 [13:51<13:24, 53.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  61% 66304/109234 [13:55<12:45, 56.07it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  61% 66560/109234 [13:59<11:37, 61.14it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  61% 66816/109234 [14:01<10:23, 68.04it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  61% 67072/109234 [14:06<10:55, 64.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  62% 67328/109234 [14:09<10:26, 66.88it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  62% 67584/109234 [14:12<09:16, 74.80it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  62% 67840/109234 [14:15<08:59, 76.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  62% 68096/109234 [14:20<10:11, 67.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  63% 68352/109234 [14:23<09:21, 72.82it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  63% 68608/109234 [14:25<08:37, 78.46it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  63% 68864/109234 [14:28<08:04, 83.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  63% 69120/109234 [14:33<09:22, 71.28it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  64% 69376/109234 [14:36<09:00, 73.78it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  64% 69632/109234 [14:39<08:23, 78.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  64% 69888/109234 [14:41<07:45, 84.58it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  64% 70144/109234 [14:46<08:54, 73.17it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  64% 70400/109234 [14:49<08:32, 75.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  65% 70656/109234 [14:53<08:46, 73.21it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  65% 70912/109234 [14:56<08:44, 73.03it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  65% 71168/109234 [15:01<09:27, 67.05it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  65% 71424/109234 [15:04<08:37, 72.99it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  66% 71680/109234 [15:06<08:03, 77.71it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  66% 71936/109234 [15:09<07:43, 80.50it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  66% 72192/109234 [15:13<08:17, 74.50it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  66% 72448/109234 [15:16<07:50, 78.11it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  67% 72704/109234 [15:19<07:25, 82.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  67% 72960/109234 [15:22<06:58, 86.58it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  67% 73216/109234 [15:26<07:57, 75.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  67% 73472/109234 [15:29<07:41, 77.44it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  67% 73728/109234 [15:32<07:16, 81.38it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  68% 73984/109234 [15:35<07:02, 83.49it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  68% 74240/109234 [15:39<07:47, 74.88it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  68% 74496/109234 [15:42<07:19, 78.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  68% 74752/109234 [15:45<07:16, 78.91it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  69% 75008/109234 [15:50<08:06, 70.33it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  69% 75264/109234 [15:52<07:27, 75.84it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  69% 75520/109234 [15:55<07:11, 78.17it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  69% 75776/109234 [15:58<06:45, 82.46it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  70% 76032/109234 [16:02<07:10, 77.12it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  70% 76288/109234 [16:06<07:49, 70.16it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  70% 76544/109234 [16:09<07:18, 74.49it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  70% 76800/109234 [16:12<06:52, 78.61it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  71% 77056/109234 [16:16<07:32, 71.15it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  71% 77312/109234 [16:20<07:14, 73.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  71% 77568/109234 [16:23<07:02, 74.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  71% 77824/109234 [16:26<06:36, 79.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  71% 78080/109234 [16:30<06:59, 74.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  72% 78336/109234 [16:33<06:39, 77.32it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  72% 78592/109234 [16:35<06:16, 81.34it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  72% 78848/109234 [16:38<06:07, 82.77it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  72% 79104/109234 [16:43<06:46, 74.05it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  73% 79360/109234 [16:46<06:25, 77.54it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  73% 79616/109234 [16:48<05:56, 83.03it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  73% 79872/109234 [16:51<05:51, 83.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  73% 80128/109234 [16:55<06:21, 76.39it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  74% 80384/109234 [16:59<06:14, 76.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  74% 80640/109234 [17:01<05:48, 82.10it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  74% 80896/109234 [17:04<05:24, 87.32it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  74% 81152/109234 [17:07<05:43, 81.70it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  75% 81408/109234 [17:10<05:39, 81.90it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  75% 81664/109234 [17:14<06:01, 76.37it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  75% 81920/109234 [17:17<05:50, 78.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  75% 82176/109234 [17:22<06:16, 71.78it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  75% 82432/109234 [17:25<05:55, 75.44it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  76% 82688/109234 [17:27<05:34, 79.34it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  76% 82944/109234 [17:30<05:20, 82.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  76% 83200/109234 [17:34<05:47, 74.84it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  76% 83456/109234 [17:37<05:25, 79.10it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  77% 83712/109234 [17:40<05:06, 83.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  77% 83968/109234 [17:43<04:49, 87.21it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  77% 84224/109234 [17:47<05:19, 78.30it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  77% 84480/109234 [17:50<05:13, 78.86it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  78% 84736/109234 [17:53<05:03, 80.60it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  78% 84992/109234 [17:56<04:50, 83.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  78% 85248/109234 [18:00<05:16, 75.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  78% 85504/109234 [18:03<05:04, 78.05it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  79% 85760/109234 [18:06<04:58, 78.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  79% 86016/109234 [18:10<05:28, 70.70it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  79% 86272/109234 [18:13<05:01, 76.10it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  79% 86528/109234 [18:16<04:52, 77.60it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  79% 86784/109234 [18:19<04:38, 80.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  80% 87040/109234 [18:24<05:10, 71.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  80% 87296/109234 [18:28<05:20, 68.52it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  80% 87552/109234 [18:32<05:36, 64.37it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  80% 87808/109234 [18:37<05:43, 62.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  81% 88064/109234 [18:43<06:30, 54.16it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  81% 88320/109234 [18:48<06:28, 53.77it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  81% 88576/109234 [18:53<06:32, 52.64it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  81% 88832/109234 [18:58<06:33, 51.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  82% 89088/109234 [19:05<07:04, 47.48it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  82% 89344/109234 [19:09<06:47, 48.76it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  82% 89600/109234 [19:14<06:35, 49.67it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  82% 89856/109234 [19:19<06:16, 51.53it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  82% 90112/109234 [19:25<06:40, 47.75it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  83% 90368/109234 [19:30<06:29, 48.49it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  83% 90624/109234 [19:35<06:18, 49.22it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  83% 90880/109234 [19:40<06:12, 49.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  83% 91136/109234 [19:48<06:50, 44.09it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  84% 91392/109234 [19:53<06:29, 45.75it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  84% 91648/109234 [19:56<05:34, 52.58it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  84% 91904/109234 [19:59<04:56, 58.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  84% 92160/109234 [20:04<04:50, 58.74it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  85% 92416/109234 [20:07<04:25, 63.35it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  85% 92672/109234 [20:12<04:34, 60.25it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  85% 92928/109234 [20:15<04:07, 65.86it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  85% 93184/109234 [20:19<04:09, 64.35it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  86% 93440/109234 [20:22<03:52, 67.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  86% 93696/109234 [20:25<03:32, 73.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  86% 93952/109234 [20:28<03:19, 76.79it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  86% 94208/109234 [20:32<03:28, 72.21it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  86% 94464/109234 [20:35<03:11, 76.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  87% 94720/109234 [20:38<03:05, 78.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  87% 94976/109234 [20:41<03:01, 78.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  87% 95232/109234 [20:45<03:16, 71.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  87% 95488/109234 [20:48<03:01, 75.86it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  88% 95744/109234 [20:52<02:54, 77.24it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  88% 96000/109234 [20:56<03:05, 71.46it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  88% 96256/109234 [20:58<02:45, 78.30it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  88% 96512/109234 [21:01<02:39, 79.87it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  89% 96768/109234 [21:05<02:36, 79.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  89% 97024/109234 [21:09<02:44, 74.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  89% 97280/109234 [21:11<02:29, 80.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  89% 97536/109234 [21:14<02:15, 86.08it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  90% 97792/109234 [21:17<02:13, 85.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  90% 98048/109234 [21:22<02:36, 71.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  90% 98304/109234 [21:25<02:31, 72.34it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  90% 98560/109234 [21:28<02:17, 77.70it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  90% 98816/109234 [21:30<02:06, 82.68it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  91% 99072/109234 [21:34<02:11, 77.25it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  91% 99328/109234 [21:37<02:04, 79.54it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  91% 99584/109234 [21:40<01:56, 82.95it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  91% 99840/109234 [21:43<01:49, 85.80it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  92% 100096/109234 [21:47<01:58, 77.25it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  92% 100352/109234 [21:49<01:47, 82.25it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  92% 100608/109234 [21:52<01:42, 84.38it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  92% 100864/109234 [21:55<01:38, 84.63it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  93% 101120/109234 [21:59<01:44, 77.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  93% 101376/109234 [22:02<01:38, 79.82it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  93% 101632/109234 [22:05<01:28, 85.49it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  93% 101888/109234 [22:08<01:26, 85.39it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  94% 102144/109234 [22:12<01:34, 74.82it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  94% 102400/109234 [22:15<01:29, 76.58it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  94% 102656/109234 [22:18<01:22, 79.76it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  94% 102912/109234 [22:21<01:16, 82.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  94% 103168/109234 [22:26<01:23, 72.68it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  95% 103424/109234 [22:29<01:21, 71.66it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  95% 103680/109234 [22:33<01:17, 71.92it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  95% 103936/109234 [22:36<01:08, 77.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  95% 104192/109234 [22:40<01:10, 71.87it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  96% 104448/109234 [22:43<01:02, 76.16it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  96% 104704/109234 [22:46<00:58, 78.05it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  96% 104960/109234 [22:48<00:51, 82.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  96% 105216/109234 [22:53<00:54, 73.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  97% 105472/109234 [22:55<00:46, 80.50it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  97% 105728/109234 [22:58<00:40, 86.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  97% 105984/109234 [23:00<00:36, 87.98it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  97% 106240/109234 [23:05<00:38, 78.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  97% 106496/109234 [23:07<00:32, 83.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  98% 106752/109234 [23:10<00:28, 88.22it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  98% 107008/109234 [23:14<00:27, 80.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  98% 107264/109234 [23:17<00:24, 78.92it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  98% 107520/109234 [23:20<00:21, 80.70it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  99% 107776/109234 [23:22<00:16, 87.17it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  99% 108032/109234 [23:26<00:15, 79.86it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  99% 108288/109234 [23:29<00:11, 83.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  99% 108544/109234 [23:31<00:07, 88.66it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks: 100% 108800/109234 [23:36<00:05, 76.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks: 100% 109234/109234 [23:42<00:00, 76.80it/s]

Batches:   0%|          | 0/6 [00:00<?, ?it/s]

Finished inserting all chunks.

Inserted 109234 chunks
Total time: 1426.36 seconds
Avg time per chunk: 0.0131 sec

In [42]:
print("Collection count:", db_section.collection.count())

Collection count: 109234

### Inspect a few stored documents

In [29]:
sample = db_section.collection.get(
    limit=5,
    include=["documents", "metadatas", "embeddings"]
)

for i in range(len(sample["ids"])):
    print("\nID:", sample["ids"][i])
    print("PMID:", sample["metadatas"][i]["pmid"])
    print("Section:", sample["metadatas"][i]["section"])
    print("Text preview:", sample["documents"][i][:200])
    print("Embedding length:", len(sample["embeddings"][i]))

Failed to send telemetry event CollectionGetEvent: capture() takes 1 positional argument but 3 were given

ID: 10024311_ABSTRACT_0
PMID: 10024311
Section: ABSTRACT
Text preview: Vascular endothelial cells regulate vascular smooth muscle tone through Ca2+-dependent production and release of vasoactive molecules. Phospholamban (PLB) is a 24- to 27-kDa phosphoprotein that modula
Embedding length: 768

ID: 10024311_ABSTRACT_1
PMID: 10024311
Section: ABSTRACT
Text preview: . These data indicate that PLB is present and modulates vascular function as a result of its actions in endothelial cells. The presence of PLB in endothelial cells opens new fields for investigation o
Embedding length: 768

ID: 10024311_TITLE
PMID: 10024311
Section: TITLE
Text preview: Phospholamban is present in endothelial cells and modulates endothelium-dependent relaxation. Evidence from phospholamban gene-ablated mice.
Embedding length: 768

ID: 10024707_AIM_0
PMID: 10024707
Section: AIM
Text preview: To evaluate a simple, ear acupuncture treatment for the cessation of smoking.
Embedding length: 768

ID: 10024707_BACKGROUND_0
PMID: 10024707
Section: BACKGROUND
Text preview: Tobacco smoking is a major cause of preventable disease and premature death. Physicians should play an active role in the control of smoking by encouraging cessation and helping the smoker to choose t
Embedding length: 768

### Run a retrieval test

In [41]:
query = "What causes Alzheimer's disease?"

results = db_section.query(query, n_results=3)

for i in range(len(results["documents"][0])):
    print("\nResult", i+1)
    print(results["documents"][0][i][:300])
    print("PMID:", results["metadatas"][0][i]["pmid"])

Result 1
The Infectious Etiology of Alzheimer's Disease.
PMID: 28294067

Result 2
Alzheimer's disease is thought to be caused by increased formations of neurotoxic amyloid beta (A beta) peptides, which give rise to the hallmark amyloid plaques. Therefore, pharmacological agents that reduce A beta formation may be of therapeutic benefit.
PMID: 19527190

Result 3
Mutations in the amyloid precursor protein gene were the first to be recognized as a cause of Alzheimer's disease (AD).
PMID: 20523046

### Check similarity scores

In [31]:
for i, dist in enumerate(results["distances"][0]):
    print(f"Result {i+1} distance:", dist)

Result 1 distance: 20.033445358276367
Result 2 distance: 21.020559310913086
Result 3 distance: 23.378067016601562

### Build BM25

In [32]:
import time
from rank_bm25 import BM25Okapi

# -------------------------
# Prepare documents
# -------------------------

docs = section_chunks_df["chunk_text"].tolist()

start_total = time.time()

# -------------------------
# Tokenize with spaCy
# -------------------------

start_token = time.time()

tokenized_docs = spacy_tokenize_texts(docs)

end_token = time.time()

print(f"Tokenization completed: {len(tokenized_docs)} docs")
print(f"Tokenization time: {end_token - start_token:.2f} seconds")

# -------------------------
# Build BM25 index
# -------------------------

start_bm25 = time.time()

bm25_section = BM25Okapi(tokenized_docs)

end_bm25 = time.time()

print("BM25 index built:", len(tokenized_docs))
print(f"BM25 build time: {end_bm25 - start_bm25:.2f} seconds")

# -------------------------
# Total time
# -------------------------

end_total = time.time()

print(f"Total pipeline time: {end_total - start_total:.2f} seconds")

spaCy tokenizing: 100% 109234/109234 [04:30<00:00, 404.16it/s]

Tokenization completed: 109234 docs
Tokenization time: 270.41 seconds
BM25 index built: 109234
BM25 build time: 2.77 seconds
Total pipeline time: 273.18 seconds

### Save BM25 Index

In [35]:
import pickle

bm25_path = BM25_DIR / "section_400token.pkl"

with open(bm25_path, "wb") as f:
    pickle.dump(bm25_section, f)

print("BM25 index saved to:", bm25_path)

BM25 index saved to: /workspace/data/bm25_index/section_400token.pkl

### Verify BM25 Retrieval

In [36]:
query = "amyloid beta plaque formation in Alzheimer's disease"

tokenized_query = spacy_tokenize_texts([query])[0]

scores = bm25_section.get_scores(tokenized_query)

import numpy as np

top_k = 10
top_idx = np.argsort(scores)[-top_k:][::-1]

results = section_chunks_df.iloc[top_idx]

results[["pmid", "section", "chunk_text"]]

spaCy tokenizing: 100% 1/1 [00:00<00:00, 363.90it/s]

,pmid,section,chunk_text
101172,29080524,TITLE,Oxidative stress and the amyloid beta peptide ...
25981,19527190,BACKGROUND,Alzheimer's disease is thought to be caused by...
22248,18191617,TITLE,Imaging of amyloid beta in Alzheimer's disease...
11631,20375655,TITLE,Safety and changes in plasma and cerebrospinal...
3983,21459773,TITLE,Impaired mitochondrial dynamics and abnormal i...
23055,21342558,BACKGROUND,Beta-site amyloid precursor protein cleaving e...
14659,20816785,ABSTRACT,There is strong evidence that intracellular ca...
80257,34198582,ABSTRACT,A large body of clinical and nonclinical evide...
97601,38095822,ABSTRACT,The approval of lecanemab by the US Food and D...
101158,35892582,TITLE,Human Palatine Tonsils Are Linked to Alzheimer...

## 2. Fixed-Length Chunking (500 Characters)

In [46]:
fixed_chunks_df = pd.read_csv(f"{CHUNK_DIR}/chunks_fixed500char.csv")

In [47]:
db_fixed = ChromaManager(
    base_directory=VECTOR_DIR,
    chunk_strategy="fixed_500char",
    embedding_model="pubmedbert",
    collection_name="medical_rag"
)

Loading embedding model: pritamdeka/S-PubMedBert-MS-MARCO

/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given

Vector DB ready → /workspace/data/vector_store/fixed_500char/pubmedbert

### Embedding Generation and Vector Database Construction

In [48]:
db_fixed.reset()

Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given

Collection reset.

In [49]:
import time

start = time.time()

db_fixed.add_chunks(fixed_chunks_df)

elapsed = time.time() - start

print(f"\nInserted {len(fixed_chunks_df)} chunks")
print(f"Total time: {elapsed:.2f} seconds")
print(f"Avg time per chunk: {elapsed/len(fixed_chunks_df):.4f} sec")

Preparing chunks:   0% 0/176626 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Failed to send telemetry event CollectionAddEvent: capture() takes 1 positional argument but 3 were given
Preparing chunks:   0% 256/176626 [00:03<42:22, 69.37it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   0% 512/176626 [00:07<41:55, 70.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   0% 768/176626 [00:11<42:12, 69.45it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   1% 1024/176626 [00:14<42:53, 68.25it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   1% 1280/176626 [00:18<42:36, 68.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   1% 1536/176626 [00:22<42:39, 68.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   1% 1792/176626 [00:26<42:35, 68.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   1% 2048/176626 [00:30<44:06, 65.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   1% 2304/176626 [00:34<44:14, 65.68it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   1% 2560/176626 [00:38<44:06, 65.78it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   2% 2816/176626 [00:41<43:42, 66.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   2% 3072/176626 [00:45<43:18, 66.78it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   2% 3328/176626 [00:48<38:16, 75.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   2% 3584/176626 [00:50<34:19, 84.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   2% 3840/176626 [00:52<30:23, 94.74it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   2% 4096/176626 [00:57<37:37, 76.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   2% 4352/176626 [01:01<41:54, 68.51it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   3% 4608/176626 [01:06<46:47, 61.26it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   3% 4864/176626 [01:11<49:04, 58.34it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   3% 5120/176626 [01:16<51:12, 55.82it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   3% 5376/176626 [01:21<52:14, 54.64it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   3% 5632/176626 [01:26<52:01, 54.79it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   3% 5888/176626 [01:31<52:14, 54.48it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   3% 6144/176626 [01:34<47:03, 60.38it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   4% 6400/176626 [01:36<39:44, 71.39it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   4% 6656/176626 [01:38<34:33, 81.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   4% 6912/176626 [01:40<30:56, 91.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   4% 7168/176626 [01:43<31:31, 89.61it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   4% 7424/176626 [01:45<28:04, 100.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   4% 7680/176626 [01:47<26:06, 107.86it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   4% 7936/176626 [01:49<24:51, 113.13it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   5% 8192/176626 [01:53<31:09, 90.10it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   5% 8448/176626 [01:56<30:18, 92.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   5% 8704/176626 [01:58<27:52, 100.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   5% 8960/176626 [02:00<26:59, 103.50it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   5% 9216/176626 [02:03<29:34, 94.35it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   5% 9472/176626 [02:05<27:47, 100.24it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   6% 9728/176626 [02:07<26:29, 105.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   6% 9984/176626 [02:09<24:36, 112.88it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   6% 10240/176626 [02:13<27:55, 99.30it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   6% 10496/176626 [02:15<27:07, 102.07it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   6% 10752/176626 [02:17<26:16, 105.22it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   6% 11008/176626 [02:20<27:18, 101.05it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   6% 11264/176626 [02:22<26:53, 102.52it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   7% 11520/176626 [02:25<26:06, 105.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   7% 11776/176626 [02:27<25:45, 106.64it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   7% 12032/176626 [02:30<27:22, 100.19it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   7% 12288/176626 [02:33<28:56, 94.64it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   7% 12544/176626 [02:35<26:34, 102.89it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   7% 12800/176626 [02:37<25:25, 107.37it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   7% 13056/176626 [02:41<28:44, 94.84it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   8% 13312/176626 [02:43<27:12, 100.04it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   8% 13568/176626 [02:45<25:02, 108.56it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   8% 13824/176626 [02:47<24:37, 110.18it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   8% 14080/176626 [02:50<27:20, 99.08it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   8% 14336/176626 [02:52<25:50, 104.68it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   8% 14592/176626 [02:54<23:50, 113.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   8% 14848/176626 [02:56<23:37, 114.11it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   9% 15104/176626 [02:59<26:28, 101.66it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   9% 15360/176626 [03:02<25:03, 107.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   9% 15616/176626 [03:04<24:03, 111.51it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   9% 15872/176626 [03:06<23:05, 116.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   9% 16128/176626 [03:09<26:09, 102.23it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   9% 16384/176626 [03:12<29:04, 91.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:   9% 16640/176626 [03:16<32:59, 80.81it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  10% 16896/176626 [03:20<35:18, 75.40it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  10% 17152/176626 [03:25<39:28, 67.34it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  10% 17408/176626 [03:29<38:46, 68.45it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  10% 17664/176626 [03:33<39:56, 66.32it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  10% 17920/176626 [03:36<39:12, 67.46it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  10% 18176/176626 [03:41<41:51, 63.09it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  10% 18432/176626 [03:45<41:41, 63.25it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  11% 18688/176626 [03:49<40:26, 65.09it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  11% 18944/176626 [03:51<35:18, 74.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  11% 19200/176626 [03:54<33:59, 77.20it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  11% 19456/176626 [03:56<30:17, 86.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  11% 19712/176626 [03:58<27:51, 93.90it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  11% 19968/176626 [04:01<26:58, 96.80it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  11% 20224/176626 [04:05<32:43, 79.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  12% 20480/176626 [04:07<29:24, 88.50it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  12% 20736/176626 [04:09<26:31, 97.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  12% 20992/176626 [04:11<24:41, 105.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  12% 21248/176626 [04:15<28:10, 91.89it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  12% 21504/176626 [04:17<26:10, 98.76it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  12% 21760/176626 [04:19<25:11, 102.48it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  12% 22016/176626 [04:23<29:03, 88.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  13% 22272/176626 [04:25<26:48, 95.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  13% 22528/176626 [04:27<24:37, 104.33it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  13% 22784/176626 [04:29<23:01, 111.33it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  13% 23040/176626 [04:33<26:32, 96.45it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  13% 23296/176626 [04:35<25:26, 100.45it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  13% 23552/176626 [04:37<24:42, 103.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  13% 23808/176626 [04:39<23:21, 109.04it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  14% 24064/176626 [04:43<28:12, 90.16it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  14% 24320/176626 [04:46<27:17, 93.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  14% 24576/176626 [04:48<25:31, 99.26it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  14% 24832/176626 [04:50<24:16, 104.20it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  14% 25088/176626 [04:54<27:20, 92.38it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  14% 25344/176626 [04:56<25:37, 98.37it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  14% 25600/176626 [04:58<23:43, 106.11it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  15% 25856/176626 [05:00<22:18, 112.66it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  15% 26112/176626 [05:03<25:34, 98.11it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  15% 26368/176626 [05:06<24:37, 101.72it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  15% 26624/176626 [05:08<23:51, 104.77it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  15% 26880/176626 [05:10<23:00, 108.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  15% 27136/176626 [05:14<26:00, 95.80it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  16% 27392/176626 [05:16<25:14, 98.56it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  16% 27648/176626 [05:18<24:15, 102.37it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  16% 27904/176626 [05:21<23:41, 104.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  16% 28160/176626 [05:25<28:30, 86.79it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  16% 28416/176626 [05:27<26:54, 91.79it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  16% 28672/176626 [05:29<25:10, 97.92it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  16% 28928/176626 [05:32<24:06, 102.10it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  17% 29184/176626 [05:35<26:02, 94.34it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  17% 29440/176626 [05:37<24:49, 98.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  17% 29696/176626 [05:39<23:20, 104.93it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  17% 29952/176626 [05:41<22:55, 106.63it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  17% 30208/176626 [05:45<24:57, 97.80it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  17% 30464/176626 [05:47<23:34, 103.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  17% 30720/176626 [05:49<22:30, 108.03it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  18% 30976/176626 [05:51<22:01, 110.23it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  18% 31232/176626 [05:54<24:43, 97.98it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  18% 31488/176626 [05:57<23:33, 102.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  18% 31744/176626 [05:59<23:19, 103.53it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  18% 32000/176626 [06:04<31:19, 76.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  18% 32256/176626 [06:08<31:25, 76.58it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  18% 32512/176626 [06:11<30:51, 77.84it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  19% 32768/176626 [06:13<28:12, 84.98it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  19% 33024/176626 [06:17<29:00, 82.49it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  19% 33280/176626 [06:19<26:15, 91.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  19% 33536/176626 [06:21<24:02, 99.18it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  19% 33792/176626 [06:23<22:45, 104.63it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  19% 34048/176626 [06:26<25:36, 92.81it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  19% 34304/176626 [06:29<24:08, 98.25it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  20% 34560/176626 [06:31<22:42, 104.24it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  20% 34816/176626 [06:33<23:10, 101.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  20% 35072/176626 [06:37<25:10, 93.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  20% 35328/176626 [06:39<23:27, 100.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  20% 35584/176626 [06:41<22:43, 103.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  20% 35840/176626 [06:44<24:16, 96.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  20% 36096/176626 [06:48<26:36, 88.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  21% 36352/176626 [06:50<24:07, 96.92it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  21% 36608/176626 [06:52<22:33, 103.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  21% 36864/176626 [06:54<22:49, 102.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  21% 37120/176626 [06:57<24:28, 95.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  21% 37376/176626 [07:00<22:57, 101.11it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  21% 37632/176626 [07:02<22:05, 104.89it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  21% 37888/176626 [07:04<20:56, 110.45it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  22% 38144/176626 [07:07<23:57, 96.33it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  22% 38400/176626 [07:09<22:40, 101.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  22% 38656/176626 [07:12<21:25, 107.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  22% 38912/176626 [07:14<21:01, 109.17it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  22% 39168/176626 [07:18<24:46, 92.48it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  22% 39424/176626 [07:20<23:20, 97.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  22% 39680/176626 [07:23<24:34, 92.91it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  23% 39936/176626 [07:25<22:33, 100.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  23% 40192/176626 [07:28<24:13, 93.87it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  23% 40448/176626 [07:30<22:01, 103.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  23% 40704/176626 [07:33<22:39, 99.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  23% 40960/176626 [07:35<21:26, 105.46it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  23% 41216/176626 [07:38<24:23, 92.54it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  23% 41472/176626 [07:41<22:44, 99.09it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  24% 41728/176626 [07:43<22:00, 102.18it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  24% 41984/176626 [07:45<21:18, 105.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  24% 42240/176626 [07:48<23:04, 97.03it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  24% 42496/176626 [07:50<21:47, 102.60it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  24% 42752/176626 [07:53<20:44, 107.53it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  24% 43008/176626 [07:56<24:08, 92.22it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  24% 43264/176626 [07:59<24:19, 91.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  25% 43520/176626 [08:01<23:02, 96.28it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  25% 43776/176626 [08:04<23:12, 95.39it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  25% 44032/176626 [08:08<25:23, 87.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  25% 44288/176626 [08:10<23:32, 93.67it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  25% 44544/176626 [08:12<22:58, 95.81it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  25% 44800/176626 [08:15<21:29, 102.21it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  26% 45056/176626 [08:18<23:43, 92.45it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  26% 45312/176626 [08:20<22:05, 99.10it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  26% 45568/176626 [08:22<20:58, 104.16it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  26% 45824/176626 [08:25<20:27, 106.58it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  26% 46080/176626 [08:28<23:57, 90.84it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  26% 46336/176626 [08:31<23:13, 93.51it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  26% 46592/176626 [08:33<21:25, 101.17it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  27% 46848/176626 [08:35<20:36, 104.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  27% 47104/176626 [08:39<23:39, 91.26it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  27% 47360/176626 [08:41<22:26, 95.98it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  27% 47616/176626 [08:44<23:54, 89.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  27% 47872/176626 [08:48<26:01, 82.45it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  27% 48128/176626 [08:53<31:07, 68.80it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  27% 48384/176626 [08:57<30:15, 70.63it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  28% 48640/176626 [08:59<26:00, 82.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  28% 48896/176626 [09:01<23:25, 90.91it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  28% 49152/176626 [09:04<24:58, 85.09it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  28% 49408/176626 [09:07<23:51, 88.87it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  28% 49664/176626 [09:09<22:33, 93.80it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  28% 49920/176626 [09:11<21:19, 99.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  28% 50176/176626 [09:15<23:44, 88.77it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  29% 50432/176626 [09:17<22:09, 94.93it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  29% 50688/176626 [09:19<20:33, 102.10it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  29% 50944/176626 [09:22<20:16, 103.32it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  29% 51200/176626 [09:26<23:35, 88.62it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  29% 51456/176626 [09:29<24:22, 85.62it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  29% 51712/176626 [09:31<21:52, 95.16it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  29% 51968/176626 [09:33<20:25, 101.68it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  30% 52224/176626 [09:37<23:21, 88.75it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  30% 52480/176626 [09:39<22:09, 93.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  30% 52736/176626 [09:41<20:27, 100.93it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  30% 52992/176626 [09:43<18:39, 110.46it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  30% 53248/176626 [09:47<22:25, 91.68it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  30% 53504/176626 [09:49<21:16, 96.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  30% 53760/176626 [09:51<19:30, 105.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  31% 54016/176626 [09:55<22:10, 92.18it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  31% 54272/176626 [09:57<21:22, 95.38it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  31% 54528/176626 [09:59<19:30, 104.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  31% 54784/176626 [10:01<18:45, 108.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  31% 55040/176626 [10:05<21:21, 94.90it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  31% 55296/176626 [10:07<21:30, 94.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  31% 55552/176626 [10:10<20:26, 98.71it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  32% 55808/176626 [10:12<19:48, 101.66it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  32% 56064/176626 [10:16<23:05, 87.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  32% 56320/176626 [10:18<21:35, 92.85it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  32% 56576/176626 [10:20<19:48, 101.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  32% 56832/176626 [10:22<18:47, 106.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  32% 57088/176626 [10:26<21:39, 91.98it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  32% 57344/176626 [10:28<20:20, 97.72it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  33% 57600/176626 [10:30<18:54, 104.95it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  33% 57856/176626 [10:32<17:29, 113.18it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  33% 58112/176626 [10:36<20:22, 96.92it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  33% 58368/176626 [10:38<19:51, 99.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  33% 58624/176626 [10:40<18:48, 104.58it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  33% 58880/176626 [10:42<17:37, 111.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  33% 59136/176626 [10:46<20:59, 93.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  34% 59392/176626 [10:49<20:50, 93.77it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  34% 59648/176626 [10:51<19:16, 101.14it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  34% 59904/176626 [10:53<18:34, 104.75it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  34% 60160/176626 [10:57<22:16, 87.16it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  34% 60416/176626 [10:59<20:32, 94.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  34% 60672/176626 [11:01<19:10, 100.81it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  34% 60928/176626 [11:04<18:19, 105.19it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  35% 61184/176626 [11:08<21:28, 89.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  35% 61440/176626 [11:10<20:10, 95.18it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  35% 61696/176626 [11:12<19:00, 100.77it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  35% 61952/176626 [11:14<17:46, 107.54it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  35% 62208/176626 [11:18<21:08, 90.22it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  35% 62464/176626 [11:20<20:00, 95.12it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  36% 62720/176626 [11:23<19:17, 98.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  36% 62976/176626 [11:25<18:08, 104.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  36% 63232/176626 [11:30<23:13, 81.34it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  36% 63488/176626 [11:33<24:46, 76.09it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  36% 63744/176626 [11:37<25:53, 72.67it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  36% 64000/176626 [11:43<30:12, 62.13it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  36% 64256/176626 [11:47<30:21, 61.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  37% 64512/176626 [11:51<30:16, 61.73it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  37% 64768/176626 [11:55<29:26, 63.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  37% 65024/176626 [12:00<32:16, 57.63it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  37% 65280/176626 [12:04<31:10, 59.51it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  37% 65536/176626 [12:08<30:42, 60.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  37% 65792/176626 [12:12<29:28, 62.67it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  37% 66048/176626 [12:18<32:37, 56.50it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  38% 66304/176626 [12:21<30:36, 60.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  38% 66560/176626 [12:25<28:59, 63.26it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  38% 66816/176626 [12:29<28:45, 63.66it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  38% 67072/176626 [12:34<30:56, 59.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  38% 67328/176626 [12:38<30:15, 60.20it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  38% 67584/176626 [12:42<28:50, 63.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  38% 67840/176626 [12:45<26:32, 68.32it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  39% 68096/176626 [12:48<26:18, 68.75it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  39% 68352/176626 [12:51<23:28, 76.89it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  39% 68608/176626 [12:53<20:33, 87.55it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  39% 68864/176626 [12:55<18:49, 95.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  39% 69120/176626 [12:58<20:46, 86.28it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  39% 69376/176626 [13:01<19:39, 90.90it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  39% 69632/176626 [13:03<18:23, 96.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  40% 69888/176626 [13:06<18:24, 96.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  40% 70144/176626 [13:09<20:09, 88.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  40% 70400/176626 [13:12<18:56, 93.45it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  40% 70656/176626 [13:14<18:05, 97.66it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  40% 70912/176626 [13:17<18:28, 95.40it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  40% 71168/176626 [13:21<21:12, 82.85it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  40% 71424/176626 [13:23<19:38, 89.25it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  41% 71680/176626 [13:25<18:15, 95.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  41% 71936/176626 [13:28<17:24, 100.21it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  41% 72192/176626 [13:31<19:33, 89.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  41% 72448/176626 [13:34<18:26, 94.15it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  41% 72704/176626 [13:36<16:49, 102.93it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  41% 72960/176626 [13:38<16:23, 105.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  41% 73216/176626 [13:41<18:36, 92.60it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  42% 73472/176626 [13:44<17:24, 98.71it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  42% 73728/176626 [13:46<16:52, 101.61it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  42% 73984/176626 [13:48<16:17, 105.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  42% 74240/176626 [13:52<18:23, 92.76it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  42% 74496/176626 [13:54<17:41, 96.20it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  42% 74752/176626 [13:56<16:24, 103.46it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  42% 75008/176626 [14:01<20:32, 82.44it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  43% 75264/176626 [14:03<18:39, 90.54it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  43% 75520/176626 [14:05<17:27, 96.52it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  43% 75776/176626 [14:07<16:20, 102.87it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  43% 76032/176626 [14:11<18:36, 90.13it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  43% 76288/176626 [14:13<17:16, 96.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  43% 76544/176626 [14:15<16:15, 102.64it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  43% 76800/176626 [14:18<15:41, 106.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  44% 77056/176626 [14:21<17:52, 92.85it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  44% 77312/176626 [14:23<16:42, 99.11it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  44% 77568/176626 [14:25<15:46, 104.61it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  44% 77824/176626 [14:28<15:47, 104.24it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  44% 78080/176626 [14:31<17:43, 92.66it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  44% 78336/176626 [14:34<16:57, 96.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  44% 78592/176626 [14:36<15:52, 102.95it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  45% 78848/176626 [14:39<16:33, 98.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  45% 79104/176626 [14:44<21:00, 77.38it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  45% 79360/176626 [14:48<23:17, 69.61it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  45% 79616/176626 [14:51<20:36, 78.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  45% 79872/176626 [14:53<19:04, 84.55it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  45% 80128/176626 [14:57<20:14, 79.45it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  46% 80384/176626 [14:59<18:08, 88.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  46% 80640/176626 [15:01<16:39, 96.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  46% 80896/176626 [15:03<15:06, 105.62it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  46% 81152/176626 [15:06<16:43, 95.10it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  46% 81408/176626 [15:08<15:36, 101.64it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  46% 81664/176626 [15:11<15:31, 101.91it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  46% 81920/176626 [15:13<14:45, 107.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  47% 82176/176626 [15:16<16:50, 93.51it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  47% 82432/176626 [15:19<15:42, 99.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  47% 82688/176626 [15:21<15:50, 98.86it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  47% 82944/176626 [15:23<14:54, 104.75it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  47% 83200/176626 [15:27<17:09, 90.72it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  47% 83456/176626 [15:29<15:58, 97.23it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  47% 83712/176626 [15:31<15:09, 102.13it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  48% 83968/176626 [15:33<13:56, 110.76it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  48% 84224/176626 [15:37<16:01, 96.10it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  48% 84480/176626 [15:39<14:55, 102.93it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  48% 84736/176626 [15:41<14:25, 106.21it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  48% 84992/176626 [15:43<13:40, 111.74it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  48% 85248/176626 [15:47<16:42, 91.16it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  48% 85504/176626 [15:50<16:03, 94.62it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  49% 85760/176626 [15:52<14:43, 102.87it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  49% 86016/176626 [15:55<16:27, 91.71it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  49% 86272/176626 [15:57<15:23, 97.85it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  49% 86528/176626 [15:59<14:19, 104.86it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  49% 86784/176626 [16:02<14:42, 101.78it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  49% 87040/176626 [16:06<16:37, 89.82it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  49% 87296/176626 [16:08<15:40, 94.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  50% 87552/176626 [16:10<15:05, 98.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  50% 87808/176626 [16:13<14:35, 101.48it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  50% 88064/176626 [16:16<16:27, 89.64it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  50% 88320/176626 [16:18<15:12, 96.78it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  50% 88576/176626 [16:21<14:15, 102.88it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  50% 88832/176626 [16:23<13:29, 108.50it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  50% 89088/176626 [16:26<15:35, 93.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  51% 89344/176626 [16:28<14:27, 100.58it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  51% 89600/176626 [16:31<14:13, 101.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  51% 89856/176626 [16:33<13:52, 104.17it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  51% 90112/176626 [16:37<16:07, 89.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  51% 90368/176626 [16:39<15:30, 92.73it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  51% 90624/176626 [16:42<15:24, 92.98it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  51% 90880/176626 [16:44<14:18, 99.87it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  52% 91136/176626 [16:48<16:22, 86.98it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  52% 91392/176626 [16:51<15:37, 90.90it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  52% 91648/176626 [16:53<14:11, 99.84it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  52% 91904/176626 [16:55<13:19, 106.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  52% 92160/176626 [16:58<15:18, 91.95it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  52% 92416/176626 [17:01<14:44, 95.17it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  52% 92672/176626 [17:03<14:08, 98.92it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  53% 92928/176626 [17:05<13:11, 105.81it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  53% 93184/176626 [17:09<15:04, 92.25it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  53% 93440/176626 [17:11<14:05, 98.33it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  53% 93696/176626 [17:13<13:07, 105.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  53% 93952/176626 [17:15<12:42, 108.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  53% 94208/176626 [17:19<14:59, 91.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  53% 94464/176626 [17:23<17:03, 80.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  54% 94720/176626 [17:27<18:07, 75.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  54% 94976/176626 [17:30<17:56, 75.88it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  54% 95232/176626 [17:34<18:15, 74.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  54% 95488/176626 [17:36<16:07, 83.90it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  54% 95744/176626 [17:38<14:13, 94.76it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  54% 96000/176626 [17:42<15:53, 84.55it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  54% 96256/176626 [17:44<14:36, 91.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  55% 96512/176626 [17:46<13:25, 99.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  55% 96768/176626 [17:48<12:20, 107.77it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  55% 97024/176626 [17:51<13:52, 95.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  55% 97280/176626 [17:54<13:08, 100.68it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  55% 97536/176626 [17:56<12:22, 106.45it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  55% 97792/176626 [17:58<11:35, 113.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  56% 98048/176626 [18:01<13:31, 96.78it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  56% 98304/176626 [18:04<14:06, 92.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  56% 98560/176626 [18:06<13:02, 99.80it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  56% 98816/176626 [18:08<12:17, 105.56it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  56% 99072/176626 [18:12<13:44, 94.10it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  56% 99328/176626 [18:14<13:16, 97.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  56% 99584/176626 [18:16<12:39, 101.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  57% 99840/176626 [18:19<13:09, 97.25it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  57% 100096/176626 [18:24<16:02, 79.48it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  57% 100352/176626 [18:27<15:11, 83.67it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  57% 100608/176626 [18:29<14:20, 88.32it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  57% 100864/176626 [18:31<13:15, 95.20it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  57% 101120/176626 [18:36<15:34, 80.81it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  57% 101376/176626 [18:38<14:05, 88.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  58% 101632/176626 [18:40<13:07, 95.19it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  58% 101888/176626 [18:42<12:12, 101.99it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  58% 102144/176626 [18:47<15:02, 82.54it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  58% 102400/176626 [18:49<13:50, 89.33it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  58% 102656/176626 [18:51<12:49, 96.07it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  58% 102912/176626 [18:54<12:19, 99.62it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  58% 103168/176626 [18:58<14:46, 82.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  59% 103424/176626 [19:00<13:46, 88.60it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  59% 103680/176626 [19:02<12:35, 96.53it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  59% 103936/176626 [19:05<11:55, 101.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  59% 104192/176626 [19:09<14:19, 84.30it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  59% 104448/176626 [19:11<13:32, 88.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  59% 104704/176626 [19:14<12:34, 95.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  59% 104960/176626 [19:16<11:55, 100.19it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  60% 105216/176626 [19:20<13:36, 87.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  60% 105472/176626 [19:22<12:24, 95.60it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  60% 105728/176626 [19:24<11:31, 102.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  60% 105984/176626 [19:27<12:05, 97.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  60% 106240/176626 [19:31<14:00, 83.73it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  60% 106496/176626 [19:33<12:47, 91.37it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  60% 106752/176626 [19:35<11:40, 99.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  61% 107008/176626 [19:39<13:30, 85.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  61% 107264/176626 [19:41<12:37, 91.56it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  61% 107520/176626 [19:43<11:30, 100.14it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  61% 107776/176626 [19:45<10:45, 106.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  61% 108032/176626 [19:49<13:01, 87.79it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  61% 108288/176626 [19:52<12:01, 94.74it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  61% 108544/176626 [19:54<11:08, 101.90it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  62% 108800/176626 [19:56<10:40, 105.86it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  62% 109056/176626 [20:00<12:33, 89.70it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  62% 109312/176626 [20:02<11:39, 96.28it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  62% 109568/176626 [20:04<11:11, 99.91it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  62% 109824/176626 [20:07<11:27, 97.12it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  62% 110080/176626 [20:12<14:48, 74.86it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  62% 110336/176626 [20:17<15:44, 70.19it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  63% 110592/176626 [20:19<14:22, 76.54it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  63% 110848/176626 [20:22<13:00, 84.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  63% 111104/176626 [20:25<13:42, 79.66it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  63% 111360/176626 [20:28<12:38, 86.07it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  63% 111616/176626 [20:30<11:32, 93.84it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  63% 111872/176626 [20:32<10:50, 99.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  63% 112128/176626 [20:36<12:45, 84.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  64% 112384/176626 [20:38<11:47, 90.75it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  64% 112640/176626 [20:41<11:04, 96.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  64% 112896/176626 [20:43<10:38, 99.78it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  64% 113152/176626 [20:47<12:19, 85.85it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  64% 113408/176626 [20:49<11:33, 91.09it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  64% 113664/176626 [20:52<11:18, 92.81it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  64% 113920/176626 [20:55<10:59, 95.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  65% 114176/176626 [20:58<12:20, 84.30it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  65% 114432/176626 [21:01<11:26, 90.55it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  65% 114688/176626 [21:03<10:42, 96.37it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  65% 114944/176626 [21:06<10:48, 95.10it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  65% 115200/176626 [21:09<12:01, 85.10it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  65% 115456/176626 [21:12<11:05, 91.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  66% 115712/176626 [21:14<10:32, 96.33it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  66% 115968/176626 [21:16<09:44, 103.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  66% 116224/176626 [21:20<11:08, 90.33it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  66% 116480/176626 [21:22<10:19, 97.11it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  66% 116736/176626 [21:24<09:45, 102.22it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  66% 116992/176626 [21:26<09:00, 110.34it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  66% 117248/176626 [21:30<10:40, 92.66it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  67% 117504/176626 [21:32<09:49, 100.23it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  67% 117760/176626 [21:35<10:13, 95.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  67% 118016/176626 [21:39<11:28, 85.09it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  67% 118272/176626 [21:41<10:44, 90.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  67% 118528/176626 [21:44<10:16, 94.30it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  67% 118784/176626 [21:46<09:26, 102.16it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  67% 119040/176626 [21:49<10:26, 91.86it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  68% 119296/176626 [21:51<09:47, 97.52it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  68% 119552/176626 [21:54<09:40, 98.32it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  68% 119808/176626 [21:56<09:23, 100.84it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  68% 120064/176626 [22:00<10:44, 87.81it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  68% 120320/176626 [22:02<10:06, 92.78it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  68% 120576/176626 [22:04<09:21, 99.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  68% 120832/176626 [22:07<08:49, 105.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  69% 121088/176626 [22:10<10:19, 89.61it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  69% 121344/176626 [22:13<09:38, 95.61it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  69% 121600/176626 [22:16<09:47, 93.73it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  69% 121856/176626 [22:17<08:48, 103.56it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  69% 122112/176626 [22:21<10:09, 89.50it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  69% 122368/176626 [22:24<09:49, 92.12it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  69% 122624/176626 [22:26<09:01, 99.75it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  70% 122880/176626 [22:28<08:08, 109.95it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  70% 123136/176626 [22:31<09:06, 97.95it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  70% 123392/176626 [22:33<08:41, 102.11it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  70% 123648/176626 [22:35<08:17, 106.53it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  70% 123904/176626 [22:37<07:56, 110.55it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  70% 124160/176626 [22:41<09:24, 92.86it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  70% 124416/176626 [22:44<09:23, 92.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  71% 124672/176626 [22:47<09:03, 95.62it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  71% 124928/176626 [22:49<08:28, 101.63it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  71% 125184/176626 [22:52<09:31, 90.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  71% 125440/176626 [22:55<09:39, 88.39it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  71% 125696/176626 [22:59<10:32, 80.48it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  71% 125952/176626 [23:03<11:00, 76.70it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  71% 126208/176626 [23:08<13:14, 63.48it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  72% 126464/176626 [23:12<13:09, 63.53it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  72% 126720/176626 [23:16<12:48, 64.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  72% 126976/176626 [23:20<12:37, 65.54it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  72% 127232/176626 [23:25<13:45, 59.81it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  72% 127488/176626 [23:29<13:26, 60.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  72% 127744/176626 [23:33<12:46, 63.79it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  72% 128000/176626 [23:38<13:34, 59.67it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  73% 128256/176626 [23:41<12:55, 62.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  73% 128512/176626 [23:43<10:57, 73.13it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  73% 128768/176626 [23:46<09:47, 81.49it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  73% 129024/176626 [23:50<10:40, 74.30it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  73% 129280/176626 [23:53<10:18, 76.50it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  73% 129536/176626 [23:55<09:06, 86.11it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  73% 129792/176626 [23:57<08:22, 93.14it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  74% 130048/176626 [24:01<09:17, 83.48it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  74% 130304/176626 [24:04<08:40, 89.07it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  74% 130560/176626 [24:06<07:54, 97.07it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  74% 130816/176626 [24:08<07:45, 98.40it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  74% 131072/176626 [24:12<09:02, 83.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  74% 131328/176626 [24:14<08:06, 93.12it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  74% 131584/176626 [24:17<07:30, 99.89it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  75% 131840/176626 [24:19<07:15, 102.91it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  75% 132096/176626 [24:23<08:36, 86.14it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  75% 132352/176626 [24:25<07:50, 94.19it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  75% 132608/176626 [24:27<07:29, 97.97it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  75% 132864/176626 [24:30<07:01, 103.71it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  75% 133120/176626 [24:34<08:43, 83.18it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  76% 133376/176626 [24:36<08:03, 89.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  76% 133632/176626 [24:38<07:10, 99.89it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  76% 133888/176626 [24:40<06:45, 105.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  76% 134144/176626 [24:44<07:39, 92.55it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  76% 134400/176626 [24:46<07:07, 98.82it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  76% 134656/176626 [24:48<06:39, 105.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  76% 134912/176626 [24:50<06:14, 111.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  77% 135168/176626 [24:55<07:51, 88.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  77% 135424/176626 [24:57<07:22, 93.14it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  77% 135680/176626 [24:59<06:59, 97.60it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  77% 135936/176626 [25:01<06:30, 104.18it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  77% 136192/176626 [25:06<08:38, 77.94it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  77% 136448/176626 [25:09<08:05, 82.73it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  77% 136704/176626 [25:11<07:21, 90.37it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  78% 136960/176626 [25:14<07:05, 93.26it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  78% 137216/176626 [25:18<07:57, 82.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  78% 137472/176626 [25:20<07:15, 89.93it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  78% 137728/176626 [25:23<06:58, 92.88it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  78% 137984/176626 [25:25<06:33, 98.22it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  78% 138240/176626 [25:29<07:34, 84.46it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  78% 138496/176626 [25:31<06:46, 93.91it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  79% 138752/176626 [25:33<06:17, 100.25it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  79% 139008/176626 [25:37<07:11, 87.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  79% 139264/176626 [25:39<06:33, 95.07it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  79% 139520/176626 [25:41<06:07, 101.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  79% 139776/176626 [25:43<05:40, 108.21it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  79% 140032/176626 [25:47<06:44, 90.53it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  79% 140288/176626 [25:49<06:21, 95.26it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  80% 140544/176626 [25:52<06:01, 99.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  80% 140800/176626 [25:54<05:58, 99.92it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  80% 141056/176626 [26:00<08:01, 73.91it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  80% 141312/176626 [26:04<08:33, 68.82it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  80% 141568/176626 [26:07<08:02, 72.72it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  80% 141824/176626 [26:09<07:03, 82.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  80% 142080/176626 [26:13<07:30, 76.62it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  81% 142336/176626 [26:16<06:54, 82.77it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  81% 142592/176626 [26:18<06:06, 92.74it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  81% 142848/176626 [26:20<05:46, 97.57it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  81% 143104/176626 [26:24<06:35, 84.68it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  81% 143360/176626 [26:26<06:08, 90.39it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  81% 143616/176626 [26:29<05:38, 97.66it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  81% 143872/176626 [26:31<05:21, 101.75it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  82% 144128/176626 [26:35<06:06, 88.68it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  82% 144384/176626 [26:37<05:39, 94.98it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  82% 144640/176626 [26:39<05:25, 98.24it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  82% 144896/176626 [26:42<05:36, 94.26it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  82% 145152/176626 [26:46<06:08, 85.51it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  82% 145408/176626 [26:48<05:34, 93.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  82% 145664/176626 [26:50<05:13, 98.84it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  83% 145920/176626 [26:52<04:53, 104.61it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  83% 146176/176626 [26:56<05:26, 93.34it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  83% 146432/176626 [26:58<05:10, 97.38it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  83% 146688/176626 [27:00<04:53, 102.14it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  83% 146944/176626 [27:03<04:44, 104.48it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  83% 147200/176626 [27:06<05:29, 89.19it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  83% 147456/176626 [27:09<05:06, 95.14it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  84% 147712/176626 [27:11<04:42, 102.21it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  84% 147968/176626 [27:13<04:33, 104.67it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  84% 148224/176626 [27:17<05:19, 89.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  84% 148480/176626 [27:19<04:57, 94.49it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  84% 148736/176626 [27:22<04:54, 94.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  84% 148992/176626 [27:24<04:26, 103.64it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  84% 149248/176626 [27:28<05:04, 89.85it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  85% 149504/176626 [27:30<04:44, 95.20it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  85% 149760/176626 [27:32<04:35, 97.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  85% 150016/176626 [27:36<05:09, 86.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  85% 150272/176626 [27:39<04:46, 91.92it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  85% 150528/176626 [27:41<04:36, 94.24it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  85% 150784/176626 [27:43<04:15, 101.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  86% 151040/176626 [27:47<04:39, 91.59it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  86% 151296/176626 [27:49<04:13, 100.03it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  86% 151552/176626 [27:51<04:00, 104.17it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  86% 151808/176626 [27:54<04:05, 101.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  86% 152064/176626 [27:57<04:40, 87.41it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  86% 152320/176626 [28:00<04:18, 94.18it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  86% 152576/176626 [28:03<04:28, 89.63it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  87% 152832/176626 [28:05<04:10, 94.99it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  87% 153088/176626 [28:09<04:35, 85.36it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  87% 153344/176626 [28:11<04:09, 93.30it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  87% 153600/176626 [28:14<03:59, 96.27it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  87% 153856/176626 [28:16<03:50, 98.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  87% 154112/176626 [28:20<04:19, 86.73it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  87% 154368/176626 [28:22<04:02, 91.72it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  88% 154624/176626 [28:24<03:47, 96.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  88% 154880/176626 [28:27<03:38, 99.34it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  88% 155136/176626 [28:30<04:01, 88.93it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  88% 155392/176626 [28:33<03:51, 91.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  88% 155648/176626 [28:35<03:28, 100.67it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  88% 155904/176626 [28:37<03:20, 103.30it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  88% 156160/176626 [28:41<03:41, 92.49it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  89% 156416/176626 [28:44<03:41, 91.32it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  89% 156672/176626 [28:47<03:58, 83.55it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  89% 156928/176626 [28:51<04:09, 79.04it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  89% 157184/176626 [28:55<04:22, 73.95it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  89% 157440/176626 [28:57<03:57, 80.93it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  89% 157696/176626 [28:59<03:28, 90.90it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  89% 157952/176626 [29:02<03:10, 98.18it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  90% 158208/176626 [29:05<03:35, 85.32it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  90% 158464/176626 [29:08<03:18, 91.55it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  90% 158720/176626 [29:10<02:59, 99.60it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  90% 158976/176626 [29:12<02:46, 105.74it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  90% 159232/176626 [29:16<03:17, 87.99it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  90% 159488/176626 [29:18<03:05, 92.50it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  90% 159744/176626 [29:21<02:50, 98.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  91% 160000/176626 [29:25<03:16, 84.55it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  91% 160256/176626 [29:28<03:12, 85.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  91% 160512/176626 [29:30<03:05, 87.09it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  91% 160768/176626 [29:33<02:48, 94.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  91% 161024/176626 [29:36<03:05, 84.08it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  91% 161280/176626 [29:39<02:52, 89.03it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  91% 161536/176626 [29:41<02:40, 94.04it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  92% 161792/176626 [29:44<02:33, 96.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  92% 162048/176626 [29:47<02:47, 87.18it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  92% 162304/176626 [29:49<02:30, 94.92it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  92% 162560/176626 [29:52<02:18, 101.58it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  92% 162816/176626 [29:54<02:10, 105.52it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  92% 163072/176626 [29:58<02:29, 90.88it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  92% 163328/176626 [30:00<02:22, 93.52it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  93% 163584/176626 [30:02<02:13, 97.68it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  93% 163840/176626 [30:05<02:05, 101.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  93% 164096/176626 [30:08<02:21, 88.77it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  93% 164352/176626 [30:12<02:24, 84.75it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  93% 164608/176626 [30:14<02:12, 90.87it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  93% 164864/176626 [30:16<02:00, 97.39it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  93% 165120/176626 [30:20<02:15, 84.99it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  94% 165376/176626 [30:23<02:05, 89.77it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  94% 165632/176626 [30:25<01:56, 94.65it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  94% 165888/176626 [30:28<01:51, 96.19it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  94% 166144/176626 [30:31<02:03, 84.62it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  94% 166400/176626 [30:34<01:52, 91.08it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  94% 166656/176626 [30:36<01:42, 97.53it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  95% 166912/176626 [30:38<01:34, 103.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  95% 167168/176626 [30:42<01:47, 87.80it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  95% 167424/176626 [30:44<01:36, 95.37it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  95% 167680/176626 [30:47<01:30, 98.63it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  95% 167936/176626 [30:49<01:25, 101.15it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  95% 168192/176626 [30:54<01:47, 78.34it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  95% 168448/176626 [30:56<01:37, 84.10it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  96% 168704/176626 [30:58<01:24, 94.06it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  96% 168960/176626 [31:01<01:17, 98.89it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  96% 169216/176626 [31:04<01:23, 88.50it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  96% 169472/176626 [31:07<01:16, 93.29it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  96% 169728/176626 [31:09<01:08, 100.86it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  96% 169984/176626 [31:11<01:07, 98.85it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  96% 170240/176626 [31:15<01:12, 88.68it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  97% 170496/176626 [31:18<01:06, 92.63it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  97% 170752/176626 [31:20<01:00, 96.42it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  97% 171008/176626 [31:24<01:04, 86.83it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  97% 171264/176626 [31:26<00:58, 92.01it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  97% 171520/176626 [31:28<00:53, 94.87it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  97% 171776/176626 [31:31<00:48, 100.96it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  97% 172032/176626 [31:35<00:57, 80.19it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  98% 172288/176626 [31:39<00:56, 76.31it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  98% 172544/176626 [31:42<00:52, 78.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  98% 172800/176626 [31:44<00:43, 87.25it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  98% 173056/176626 [31:48<00:43, 82.35it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  98% 173312/176626 [31:50<00:37, 89.43it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  98% 173568/176626 [31:52<00:30, 98.73it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  98% 173824/176626 [31:55<00:28, 98.52it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  99% 174080/176626 [31:58<00:28, 89.47it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  99% 174336/176626 [32:01<00:24, 93.70it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  99% 174592/176626 [32:03<00:20, 99.73it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  99% 174848/176626 [32:05<00:17, 100.02it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  99% 175104/176626 [32:09<00:16, 91.52it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  99% 175360/176626 [32:11<00:13, 95.30it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks:  99% 175616/176626 [32:13<00:10, 100.00it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks: 100% 175872/176626 [32:16<00:08, 93.69it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks: 100% 176128/176626 [32:20<00:05, 85.22it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Preparing chunks: 100% 176626/176626 [32:23<00:00, 90.90it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Finished inserting all chunks.

Inserted 176626 chunks
Total time: 1944.80 seconds
Avg time per chunk: 0.0110 sec

In [56]:
print("Collection count:", db_fixed.collection.count())

Collection count: 176626

### Inspect a few stored documents

In [50]:
sample = db_fixed.collection.get(
    limit=5,
    include=["documents", "metadatas", "embeddings"]
)

for i in range(len(sample["ids"])):
    print("\nID:", sample["ids"][i])
    print("PMID:", sample["metadatas"][i]["pmid"])
    print("Section:", sample["metadatas"][i]["section"])
    print("Text preview:", sample["documents"][i][:200])
    print("Embedding length:", len(sample["embeddings"][i]))

Failed to send telemetry event CollectionGetEvent: capture() takes 1 positional argument but 3 were given

ID: 10024311_F500_0
PMID: 10024311
Section: ABSTRACT
Text preview: Vascular endothelial cells regulate vascular smooth muscle tone through Ca2+-dependent production and release of vasoactive molecules. Phospholamban (PLB) is a 24- to 27-kDa phosphoprotein that modula
Embedding length: 768

ID: 10024311_F500_1
PMID: 10024311
Section: ABSTRACT
Text preview: actility in these muscles. In the present study, we report the existence of PLB in the vascular endothelium, a nonmuscle tissue, and provide functional data on PLB regulation of vascular contractility
Embedding length: 768

ID: 10024311_F500_2
PMID: 10024311
Section: ABSTRACT
Text preview: of nitric oxide on the smooth muscle, because sodium nitroprusside-mediated relaxation in either denuded or endothelium-intact aortas was unaffected by PLB ablation. Relative to denuded vessels, relax
Embedding length: 768

ID: 10024311_F500_3
PMID: 10024311
Section: ABSTRACT
Text preview: a endothelial cells were isolated. Both reverse transcriptase-polymerase chain reaction and Western blot analyses revealed the presence of PLB in endothelial cells, which were shown to be >98% pure by
Embedding length: 768

ID: 10024311_F500_4
PMID: 10024311
Section: ABSTRACT
Text preview: ens new fields for investigation of Ca2+ regulatory pathways in nonmuscle cells and for modulation of endothelial-vascular interactions.
Embedding length: 768

### Run a retrieval test

In [51]:
query = "What causes Alzheimer's disease?"

results = db_fixed.query(query, n_results=3)

for i in range(len(results["documents"][0])):
    print("\nResult", i+1)
    print(results["documents"][0][i][:300])
    print("PMID:", results["metadatas"][0][i]["pmid"])

Failed to send telemetry event CollectionQueryEvent: capture() takes 1 positional argument but 3 were given

Result 1
Alzheimer's disease (AD) is the most frequent cause of dementia in the elderly. Few cases are familial (FAD), due to autosomal dominant mutations in presenilin-1 (PS1), presenilin-2 (PS2) or amyloid precursor protein (APP). The three proteins are involved in the generation of amyloid-beta (Aβ) pepti
PMID: 31606858

Result 2
Alzheimer's disease (AD) is the primary cause of dementia in the elderly. It remains incurable and poses a huge socio-economic challenge for developed countries with an aging population. AD manifests by progressive decline in cognitive functions and alterations in behaviour, which are the result of
PMID: 27023706

Result 3
Alzheimer's disease (AD) is the most common cause of dementia in humans. A pathological hallmark in the brain of an AD patient is extracellular amyloid plaques formed by accumulated beta-amyloid protein (Abeta), a metabolic product of amyloid precursor protein (APP). Studies have revealed a strong g
PMID: 16426772

### Check similarity scores

In [52]:
for i, dist in enumerate(results["distances"][0]):
    print(f"Result {i+1} distance:", dist)

Result 1 distance: 20.541053771972656
Result 2 distance: 20.69760513305664
Result 3 distance: 21.04430389404297

### Build BM25

In [57]:
import time
from rank_bm25 import BM25Okapi

# -------------------------
# Prepare documents
# -------------------------

docs = fixed_chunks_df["chunk_text"].tolist()

start_total = time.time()

# -------------------------
# Tokenize with spaCy
# -------------------------

start_token = time.time()

tokenized_docs = spacy_tokenize_texts(docs)

end_token = time.time()

print(f"Tokenization completed: {len(tokenized_docs)} docs")
print(f"Tokenization time: {end_token - start_token:.2f} seconds")

# -------------------------
# Build BM25 index
# -------------------------

start_bm25 = time.time()

bm25_fixed = BM25Okapi(tokenized_docs)

end_bm25 = time.time()

print("BM25 index built:", len(tokenized_docs))
print(f"BM25 build time: {end_bm25 - start_bm25:.2f} seconds")

# -------------------------
# Total time
# -------------------------

end_total = time.time()

print(f"Total pipeline time: {end_total - start_total:.2f} seconds")

spaCy tokenizing: 100% 176626/176626 [05:03<00:00, 582.68it/s]

Tokenization completed: 176626 docs
Tokenization time: 303.30 seconds
BM25 index built: 176626
BM25 build time: 2.91 seconds
Total pipeline time: 306.21 seconds

### Save BM25 Index

In [58]:
import pickle

# -------------------------
# Save BM25 index (fixed 500 chunk)
# -------------------------

bm25_path = BM25_DIR / "fixed_500char.pkl"

with open(bm25_path, "wb") as f:
    pickle.dump(bm25_fixed, f)

print("BM25 index saved to:", bm25_path)

BM25 index saved to: /workspace/data/bm25_index/fixed_500char.pkl

### Verify BM25 Retrieval

In [66]:
query = "amyloid beta plaque formation in Alzheimer's disease"

tokenized_query = spacy_tokenize_texts([query])[0]

scores = bm25_fixed.get_scores(tokenized_query)

import numpy as np

top_k = 10
top_idx = np.argsort(scores)[-top_k:][::-1]

results = fixed_chunks_df.iloc[top_idx]

results[["pmid", "section", "chunk_text"]]

spaCy tokenizing: 100% 1/1 [00:00<00:00, 380.02it/s]

            pmid   section                                         chunk_text
164358  29080524     TITLE  Oxidative stress and the amyloid beta peptide ...
37154   18191617     TITLE  Imaging of amyloid beta in Alzheimer's disease...
19386   20375655     TITLE  Safety and changes in plasma and cerebrospinal...
6653    21459773     TITLE  Impaired mitochondrial dynamics and abnormal i...
38629   21342558  ABSTRACT  ry species thought to be responsible for the n...
164338  35892582     TITLE  Human Palatine Tonsils Are Linked to Alzheimer...
37115   24199960  ABSTRACT  Cholesterol is implicated in the development o...
164425  26657517  ABSTRACT  Despite amyloid plaques, consisting of insolub...
164388  32183293     TITLE  Potential Role of Venular Amyloid in Alzheimer...
24690   20816785  ABSTRACT  There is strong evidence that intracellular ca...

In [64]:
import pickle

bm25_section = pickle.load(open(BM25_DIR / "section_400token.pkl", "rb"))
bm25_fixed500 = pickle.load(open(BM25_DIR / "fixed_500char.pkl", "rb"))

In [65]:
print("Section chunks:", len(bm25_section.doc_len))
print("Fixed500 chunks:", len(bm25_fixed500.doc_len))

Section chunks: 109234
Fixed500 chunks: 176626